/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Accounts: () => import('#controllers/accounts_controller'),
  Categories: () => import('#controllers/categories_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
}
