import CommonAlert from '~/components/CommonAlert.vue'

export default {
  title: 'Common/Alert',
  component: CommonAlert,
  parameters: {
    layout: 'fullscreen'
  },
  argTypes: {
    modelValue: { control: 'boolean', description: 'prop generated by v-model directive' },
    alert: { control: 'object', description: 'options for alert' },
    millisecondsToClose: {
      control: 'number',
      description: 'milliseconds to close alert after it have been open, default is 5000'
    }
  }
}

const Template = (args) => ({
  components: { CommonAlert },
  setup() {
    return {
      args
    }
  },
  template: `
    <div>
      <common-alert v-bind="args" />
      </div>
    `
})

const TemplateWithSlot = (args) => ({
  components: { CommonAlert },
  setup() {
    return {
      args
    }
  },
  template: `
      <common-alert v-bind="args">
        <p>default slot content</p>
      </common-alert>
    `
})

export const ComponentWithSlot = TemplateWithSlot.bind({})
ComponentWithSlot.args = {
  modelValue: true
}

export const ComponentWithCustomMessage = Template.bind({})
ComponentWithCustomMessage.args = {
  modelValue: true,
  alert: {
    message: 'props alert message',
    borderColor: 'red'
  }
}
