services:
  fr-api:
    build: .
    image: fr-api
    container_name: fr-api
    restart: unless-stopped
    depends_on:
      fr-db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3334
      LOG_LEVEL: info
      APP_KEY: ${APP_KEY:-oQMQwC6WPADrAnwtJiONTmhhRIxYg4kj}
      APP_URL: http://localhost:3334
      SESSION_DRIVER: memory
      DATABASE_URL: postgresql://user:pass@fr-db:5432/postgres?schema=public&connect_timeout=300
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - '3334:3334'
      - '4000:4000'
      - '9229:9229'
    networks:
      - webnet

  fr-db:
    image: postgres:16-alpine
    container_name: fr-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    volumes:
      - fr-db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d postgres']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - webnet

networks:
  webnet:

volumes:
  fr-db:
